site_name: CLT Base Model
plugins:
- mkdocstrings:
    enable_inventory: true
    handlers:
      python:
        selection:
          private: true
          protected: true
        options:
          show_signature_annotations: true
- search

nav:
- Home: index.md
- Python for Modelers:
    - python_resources.md
- Mathematical Formulation:
    - math_flu_components.md
    - math_transitions.md
- Flu Model Code Documentation:
    - flu_model_code_overview.md
    - flu_model_demo.md
    - flu_input_requirements.md
    - flu_components_walkthrough.md
- Creating Custom Models:
    - SIHR_components_walkthrough.md
- Code API Reference:
    - clt_base_package_reference.md
    - flu_components_reference.md
theme: 
  name: material 
  favicon: img/favicon.ico

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - markdown_katex:
      no_inline_svg: true
      insert_fonts_css: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
  - https://cdn.jsdelivr.net/npm/katex@0.13.13/dist/katex.min.js
  - https://cdn.jsdelivr.net/npm/katex@0.13.13/dist/contrib/auto-render.min.js

