site_name: CLT Base Model
plugins:
- mkdocstrings:
    enable_inventory: true
- search
nav:
- Home: index.md
- math_flu_components.md
- reference.md
theme: 
  name: material 
  favicon: images/favicon.ico

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
