site_name: CLT Base Model
plugins:
- mkdocstrings:
    enable_inventory: true
- search
nav:
- Home: index.md
- math_flu_components.md
- flu_model_code.md
- base_components_reference.md
- flu_components_reference.md
theme: 
  name: material 
  favicon: img/favicon.ico

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - markdown_katex:
      no_inline_svg: true
      insert_fonts_css: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
  - https://cdn.jsdelivr.net/npm/katex@0.13.13/dist/katex.min.js
  - https://cdn.jsdelivr.net/npm/katex@0.13.13/dist/contrib/auto-render.min.js

